name: Macos-CI

'on':
  - push
  - pull_request

permissions:
  contents: read

jobs:
  ci:
    name: macos-llvm
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX:PATH=destination -DENABLE_ROARING_TESTS=ON ..
          cmake --build . 
          ctest . --output-on-failure
          cmake --install . 
          cd ../tests/installation/find && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=../../../build/destination .. &&  cmake --build .
      - name: Build and Test (shared)
        run: |
          cmake -DBUILD_SHARED_LIBS=ON  -DCMAKE_INSTALL_PREFIX:PATH=destinationshared -DENABLE_ROARING_TESTS=ON -B buildshared
          cmake --build buildshared
          cmake --install buildshared
          cd tests/installation/find
          cmake -DCMAKE_INSTALL_PREFIX:PATH=../../../destinationshared -B buildshared
          cmake --build buildshared
          ./buildshared/repro
      - name: Build and Test Debug
        run: |
          mkdir builddebug
          cd builddebug
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=destination -DENABLE_ROARING_TESTS=ON ..
          cmake --build . 
          ctest . --output-on-failure
          cmake --install . 
          cd ../tests/installation/find && mkdir builddebug && cd builddebug && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=../../../build/destination .. &&  cmake --build .
