name: Ubuntu s390x (GCC 11)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: uraimo/run-on-arch-action@4803fad82c266c7860218e93d3024b5810c7866a # v2.6.0
        name: Test
        id: runcmd
        with:
          arch: s390x
          githubToken: ${{ github.token }}
          distro: ubuntu_latest
          install: |
            apt-get update -q -y
            apt-get install -y cmake make g++ git
          run: |
            cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_ROARING_TESTS=ON -B build
            cmake --build build -j=2
            ctest --output-on-failure --test-dir build

