name: VS17-ARM-CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    name: windows-vs17
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {arch: ARM}
          - {arch: ARM64}
    steps:
      - name: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Use cmake
        run: |
          cmake -A ${{ matrix.arch }} -DCMAKE_CROSSCOMPILING=1 -B build  &&
          cmake --build build --verbose
